name: Build and Test Xposed Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 11 (use temurin)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Install Android SDK
      - name: Install Android SDK
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          # Download and extract Android SDK command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          
          # Set environment variables for Android SDK
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
          
          # Confirm sdkmanager is available
          sdkmanager --version
          
          # Accept licenses and install required components
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      # Step 4: Set up Gradle
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
        
      # Step 5: Run Gradle build to assemble APK
      - name: Build APK
        run: |
          gradle wrapper --gradle-version 8.13
          ./gradlew assembleDebug

      # Step 6: Upload APK as artifact (using v4)
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
