name: Build Xposed Module APK

on:
  push:
    branches:
      - main  # 当 push 到 main 分支时触发
  pull_request:
    branches:
      - main  # 允许 PR 触发构建

jobs:
  build:
    runs-on: ubuntu-latest  # 在 Ubuntu 服务器上运行

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # 使用 Eclipse Temurin JDK
          java-version: '17'

      - name: 安装 Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: 初始化 Gradle Wrapper
        run: gradle wrapper  # 生成 gradlew

      - name: 赋予 gradlew 可执行权限
        run: chmod +x gradlew

      - name: 编译 APK
        run: ./gradlew assembleDebug

      - name: 上传 APK 作为构建产物
        uses: actions/upload-artifact@v4
        with:
          name: Xposed-Module-APK
          path: app/build/outputs/apk/debug/app-debug.apk
