name: Build Xposed Module

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 设置 Gradle 缓存
        uses: gradle/actions/setup-gradle@v3

      - name: 赋予 gradlew 可执行权限
        run: chmod +x gradlew

      - name: 编译 APK
        run: ./gradlew assembleDebug

      - name: 上传 APK 作为构建产物
        uses: actions/upload-artifact@v4  # 修正为 v4
        with:
          name: Xposed-Module-APK
          path: app/build/outputs/apk/debug/app-debug.apk
